### ISSUE TITLE
Error after migration to 0.14.0 and typescript 1.6.2

### ISSUE THREAD

**Issue by krtr** [s-panferov/awesome-typescript-loader#58]
After migration to awesome-typescript-loader@0.14.0 and typescript@1.6.2 I'm getting this error:

``` ERROR in [default] C:/Users/tester/Desktop/testing/test/src/app.tsx:4:28
Cannot find module './view/popup/PopupNames'. ```

my config:
```
 { 
    entry: {
        app: ["./src/app.tsx"],
    },
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
    },
    output: {
        path: path.join(__dirname, 'bin'),
        filename: '[name].bundle.js',
        publicPath: '/bin/'
    },
    module: {
        loaders: [
            {
                test: /\.tsx?$/,
                loaders: ['awesome-typescript-loader'],
                include: [path.resolve(__dirname, "src")]
            },
            {
                test: /\.json?$/,
                loaders: ['json-loader']
            }
        ]
    }

};
```
tsconfig: 
```
  "compilerOptions": {
    "target": "es6",
    "sourceMap": true,
    "jsx": "react",
    "experimentalDecorators": true,
    "experimentalAsyncFunctions": true
  },
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "useCache": true
  },
  "files": [
  "./src/app.tsx", "./typings/bundle-tsd.d.ts"
  ]
}
```

**Comment by Coderah** [comment]
try setting ```"moduleResolution": "node"``` in your tsconfig compilerOptions.

Either way this is unlikely the loaders fault.

**Comment by krtr** [comment]
>try setting "moduleResolution": "node" in your tsconfig compilerOptions.

ERROR in ./src/app.tsx
Module build failed: TypeError: Cannot read property 'resolvedModule' of undefined
 at Host.resolveModuleNames

Same error as in #58

**Comment by nelo112** [comment]
I've just started making a HelloWorld to learn TypeScript & Webpack and I got the same error:
ERROR in [default] c:/Users/m.huber/_Projects/HelloWorldWebpack/src/entry.ts:1:23
Cannot find module './hello-world'.
but the thing still compiled. I got the bundle.js which I called in the index.html and everything worked.
I then went back to Typescript version 1.5.3 and no longer get the error message.

**Comment by pepe79** [comment]
After updating to typescript 1.6.2 and awesome-typescript-loader 0.14.0 we are experiencing the same error on windows builds ONLY (Win 7), Mac OS and Linux builds DO NOT have this error.

**Comment by michael-wolfenden** [comment]
I am also seeing the same error on windows 7 with typescript 1.6.2 and awesome-typescript-loader 0.14.0

**Comment by s-panferov** [comment]
Hello everybody! Sorry for the delay, I was on vacation. Does anybody have an example app I can compile to reproduce the error? And I'll try to compile my own projects on Windows virtual machine to see if I can reproduce the error.

**Comment by krtr** [comment]
@s-panferov Here you go: https://github.com/krtr/awesome-repro

You should get: `Cannot find module './test/RootView'.`

**Comment by krtr** [comment]
Seems to be fixed at 0.15.1
Thanks!
