### ISSUE TITLE
0.15.1 Module build failed: Error: ENOENT

### ISSUE THREAD

**Issue by Andrey-Pavlov** [s-panferov/awesome-typescript-loader#77]
I use generator-gulp-angular. After update from 0.14.1 to 0.15.1  I get errors.

OS: Ubuntu
Typescript 1.6

```javascript
ERROR in ./src/app/index.module.ts
Module build failed: Error: ENOENT: no such file or directory, open '/home/xxx/xxx/src/app/index.config'
    at Error (native)

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:1:0 
File '/home/xxx/xxx/.tmp/typings/tsd.d.ts' not found.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:3:23 
Cannot find module './index.config'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:4:29 
Cannot find module './index.route'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:5:25 
Cannot find module './index.run'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:6:31 
Cannot find module './main/main.controller'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:7:34 
Cannot find module '../app/components/githubContributor/githubContributor.service'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:8:33 
Cannot find module '../app/components/webDevTec/webDevTec.service'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:9:27 
Cannot find module '../app/components/navbar/navbar.directive'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:10:29 
Cannot find module '../app/components/malarkey/malarkey.directive'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:13:20 
Cannot find namespace 'moment'.

ERROR in [default] /home/xxx/xxx/src/app/index.module.ts:18:2 
Cannot find name 'angular'.
```

**Comment by tscislo** [comment]
Same on Windows 7 and TypeScript 1.6.2
