### ISSUE TITLE
modulesTypeError: this.ts.getAutomaticTypeDirectiveNames is not a function

### ISSUE THREAD

**Issue by Veikedo** [s-panferov/awesome-typescript-loader#217]
After upgrading from 2.0.1 to 2.2.1 I got this error: 

>  build modulesTypeError: this.ts.getAutomaticTypeDirectiveNames is not a function

The full log can be found here: https://gist.github.com/Veikedo/2ec86150746ff3d0b2b830d6d9878b15

My tsconfig.json
`{
  "compilerOptions": {  
    "target": "es5",       
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "noEmitOnError": false,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitHelpers": true,
    "allowJs": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },  
  "exclude": [
    "node_modules",
    "bower_components",
    "wwwroot",
    "obj",
    "Scripts"
  ]
}`

**Comment by circy** [comment]
i have the same problem.

**Comment by locnguyen** [comment]
Same here. I'm trying to use webpack for an Ionic 2 project that was scaffolded by the CLI so I don't think I'm doing anything out of the ordinary.

**Comment by garygentry** [comment]
Same problem.

**Comment by Epenance** [comment]
Same problem here

**Comment by locnguyen** [comment]
I switched to ts-loader and it's working. That will do until this is resolved

**Comment by Veikedo** [comment]
@locnguyen I think it's better to just not upgrading :)
Just removed ^ in package.json to use exactly version

**Comment by helloncanella** [comment]
+1

**Comment by marcbuils** [comment]
Same problem.

**Comment by davidmoshal** [comment]
+1

**Comment by Veikedo** [comment]
I'm blind. Here's already an opened issue and the answer https://github.com/s-panferov/awesome-typescript-loader/issues/212#issuecomment-241340835
