### ISSUE TITLE
Weird type errors after updating from 3.5.0 -> 4.0.0

### ISSUE THREAD

**Issue by JonWallsten** [s-panferov/awesome-typescript-loader#548]
TypeScript: 2.7.1
ATL: 4.0.0
Webpack: 3.11.0
TSLint and TSC compiles without errors.

```js
// legacy.ts
/* Include all javascript files from the app */
const req = require.context('./app/', true, /^(?!.*\.test\.js$).*\.js$/);
req.keys().forEach(req);
```

```js
// vendor.ts
/* tslint:disable:no-require-imports no-var-requires */
(window as any).postal = require('../node_modules/postal/lib/postal.js');
(window as any).$ = (window as any).jQuery = require('../node_modules/jquery/dist/jquery.js');
/* tslint:enable:no-require-imports */
```

```
[at-loader] Checking started in a separate process...
[at-loader] Checking finished with 12 errors
[at-loader] TS6053: File 'C:/lib.dom.d.ts' not found.

[at-loader] TS6053: File 'C:/lib.es2015.d.ts' not found.

[at-loader] TS2318: Cannot find global type 'Array'.

[at-loader] TS2318: Cannot find global type 'Boolean'.

[at-loader] TS2318: Cannot find global type 'IArguments'.

[at-loader] TS2318: Cannot find global type 'Number'.

[at-loader] TS2318: Cannot find global type 'Object'.

[at-loader] TS2318: Cannot find global type 'RegExp'.

[at-loader] ./src/legacy.ts:3:12
    TS2339: Property 'forEach' does not exist on type '{}'.

[at-loader] ./src/vendor.ts:2:2
    TS2304: Cannot find name 'window'.

[at-loader] ./src/vendor.ts:3:2
    TS2304: Cannot find name 'window'.

[at-loader] ./src/vendor.ts:3:22
    TS2304: Cannot find name 'window'.
```

**Comment by asual** [comment]
I'm experiencing the same with both 4.0.0-0 and 5.0.0-0 (webpack 4.0.1 and ts 2.7.2).

**Comment by stoic-dev** [comment]
I am also experiencing these errors.

This is my webpack (4.1.0) config
```javascript
const DtsBundleWebpackPlugin = require('dts-bundle-webpack');

const utils = require('../utils');

module.exports = function() {
    return {
        entry: {
            main: utils.root('src', 'index.ts')
        },
        externals:{
            'reflect-metadata': {
                commonjs: 'reflect-metadata'
            }
        },
        module: {
            rules: [{
                test: /\.ts$/,
                use: [{
                    loader: 'babel-loader',
                    options: {
                        presets: ['env']
                    }
                },
                {
                    loader: 'awesome-typescript-loader'
                }],
                exclude: [
                    /config/,
                    /node_modules/,
                    /\.spec\.ts$/
                ]
            }]
        },
        node: {
            __dirname: false
        },
        output: {
            path: utils.root('dist'),
            filename: 'index.js',
            library: 'magellan-collections',
            libraryTarget: 'commonjs'
        },
        plugins: [
            new DtsBundleWebpackPlugin({
                name: 'magellan-collections',
                main: utils.root('./src/index.d.ts'),
                out: utils.root('./dist/index.d.ts'),
                removeSource: true,
                outputAsModuleFolder: true,
                emitOnIncludedFileNotFound: true
            })
        ],
        resolve: {
            extensions: [
                '.js',
                '.ts'
            ]
        },
        target: 'node'
    }
};
```

And my tsconfig (Typescript 2.7.2)
```json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "alwaysStrict": true,
        "declaration": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "lib": ["es2015"],
        "module": "esnext",
        "moduleResolution": "node",
        "noEmit": false,
        "noEmitHelpers": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "removeComments": true,
        "target": "esnext",
        "typeRoots": ["node_modules/@types"],
        "types": ["node"]
    },
    "exclude": ["node_modules", "dist", "src/**/*.spec.ts"],
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useWebpackText": true
    }
}
```

tsc and tslint also run successfully

Works fine if I revert back to my old version (3.5.0)

**Comment by narthollis** [comment]
Would it be possible to get a 4.x release with #550 in it to resolve this issue? I am not currently in a position to upgrade webpack to 4 (other plugins).

**Comment by s-panferov** [comment]
Sure

**Comment by charandas** [comment]
@s-panferov i see that you updated the [release-4](https://github.com/s-panferov/awesome-typescript-loader/tree/release-4) branch with this fix. It would be great if you can release a newer 4.x version now.

Like @narthollis i have to live with Webpack 3 for now.

**Comment by charandas** [comment]
Any news on this @s-panferov? I am asking for a 4.x release which is a dist built up and published after #550 was merged.

**Comment by alignsoft** [comment]
Any progress on a 4.x release with this fix in it? We're also not in a position to upgrade to Webpack 4 at the moment, and are running into this issue on our Windows Dev machines. Thanks!
