### ISSUE TITLE
v2.2.1 when upgraded from v2.1.1 I get this.ts.getAutomaticTypeDirectiveNames is not a function

### ISSUE THREAD

**Issue by tomaash** [s-panferov/awesome-typescript-loader#211]
After upgrading from version v2.1.1 to v2.2.1 I get this error:

ERROR in ./src/app/app.tsx
Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a function
    at State.loadTypesFromConfig (/Users/tom/Code/StartMonday/sm-web-widget/node_modules/awesome-typescript-loader/src/host.ts:148:36)
    at new State (/Users/tom/Code/StartMonday/sm-web-widget/node_modules/awesome-typescript-loader/src/host.ts:142:14)
    at Object.ensureInstance (/Users/tom/Code/StartMonday/sm-web-widget/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/Users/tom/Code/StartMonday/sm-web-widget/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/tom/Code/StartMonday/sm-web-widget/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi app

I'm on mac, my package.json: 
https://gist.github.com/tomaash/066124f97e696e482868fe8c3170f360

**Comment by tomaash** [comment]
OK, nevermind. Actually upgrading to webpack 2.1.0-beta.20 solved the issue. So just note here, v2.1.1 was still accidentally compatible with webpack 1, but v2.2.1 is not.
