### ISSUE TITLE
Error with type definitions referenced from other definition files

### ISSUE THREAD

**Issue by kucharzyk** [s-panferov/awesome-typescript-loader#194]
Hi,

I've got problem with refernces in typescript definitions like that:

```
/// <reference types="selenium-webdriver" />
```

Webpack throws error like this
```
Error in bail mode: [default] C:\dev\projects\spring-angular2-starter\shardis-ui\node_modules\@types\protractor\index.d.ts:6:0
Cannot find type definition file for 'selenium-webdriver'.
```

* Error is not specific to 'selenium-webdriver'.
* Definitions without such references works fine

I think it could be problem with awesome-typescrpt-loader

My configuration details:

package.json
```
    "@types/core-js": "0.9.28",
    "@types/hammerjs": "2.0.28",
    "@types/jasmine": "2.2.29",
    "@types/node": "4.0.29",
    "@types/protractor": "1.5.16",
    "@types/selenium-webdriver": "2.44.26",
    "@types/source-map": "0.1.26",
    "@types/uglify-js": "2.0.27",
    "@types/webpack": "1.12.29",
    "typescript": "2.1.0-dev.20160715",
```

tsconfig.json
```
{
  "buildOnSave": false,
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "removeComments": false,
    "noEmitHelpers": false,
    "noImplicitAny": false,
    "libs": [
      "es6",
      "dom"
    ],
    "strictNullChecks": false,
    "types": [
      "core-js",
      "hammerjs",
      "jasmine",
      "node",
      "selenium-webdriver",
      "protractor",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "awesomeTypescriptLoaderOptions": {
    "resolveGlobs": true,
    "forkChecker": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by JurajMlich** [comment]
+1

**Comment by metrophos** [comment]
+1

**Comment by kucharzyk** [comment]
Issue stil exists in version 2.1.0

**Comment by jhuntoo** [comment]
+1

**Comment by s-panferov** [comment]
It's very hard for me to debug on Windows. Could you please create some minimal example which I can use to reproduce the issue?

**Comment by kucharzyk** [comment]
Just add the following types:

package.js
```
...
    "@types/protractor": "1.5.16",
    "@types/selenium-webdriver": "2.44.26",
...
```

tsconfig.conf
```
...
    "types": [
      "selenium-webdriver",
      "protractor"
    ],
...
```

Protractor types reference selenium-webdriver so you can get error:
```
Error in bail mode: [default] C:\dev\projects\spring-angular2-starter\shardis-ui\node_modules\@types\protractor\index.d.ts:6:0
Cannot find type definition file for 'selenium-webdriver
```

**Comment by s-panferov** [comment]
@kucharzyk what project are you talking about?

https://github.com/kucharzyk/spring-angular2-starter ?

How to run it? I don't see any webpack.config.json in the root.

**Comment by kucharzyk** [comment]
Frontend app is in shardis-ui directory
You can build it using
'''
npm run build:prod
'''

**Comment by JurajMlich** [comment]
@s-panferov https://github.com/AngularClass/angular2-webpack-starter

**Comment by s-panferov** [comment]
Should be fixed in `awesome-typescript-loader@2.1.1`

**Comment by kucharzyk** [comment]
Tested under linux:

* It's not working with awesome-typescript-loader@2.1.0
* It's working with awesome-typescript-loader@2.1.1

Good job!!!

Thanks

**Comment by JurajMlich** [comment]
Working on Mac as well. Thanks :)

**Comment by thrandre** [comment]
Still having issues with this on version 2.1.1:

```
ERROR in [default] C:\Projects\Prover-hoved\src\UDIR.Prover.Frontend\node_modules\@types\react-dom\react-dom.server.d.ts:2:30        
Cannot find module 'react'. 
```

I'm guessing this is the culprit (from `@types/react-dom/react-dom.server.d.ts`):
```
declare module "react-dom/server" {
	import { ReactElement } from 'react'; // This should point to typings at @types/react
	
...
}
```

No compilation issues when using version prior to 2.0.3 (2.0.2 works like a charm) or when using `tsc` directly.

My `tsconfig.json` (for completeness):
```
{
	"version": "2.0",
	"compilerOptions": {
		"target": "es2015",
		"noImplicitAny": true,
		"jsx": "react",
		"sourceMap": true,
		"moduleResolution": "node",
		"allowSyntheticDefaultImports": true,
		"paths": {
			"common/components/*": ["./common/components/*"]
		},
		"baseUrl": ""
	},
	"awesomeTypescriptLoaderOptions": {
		"useBabel": true,
		"useCache": true
	},
	"exclude": [
		"node_modules"
	]
}
```

Thanks!

**Comment by admmasters** [comment]
This is happening to me as well:
`node_modules/@types/react-dom/index.d.ts:6:0
File 'node_modules/@types/react-dom/react-dom.server.d.ts' not found.`

**Comment by mweststrate** [comment]
+1

**Comment by guidojo** [comment]
+1

**Comment by nklap** [comment]
+1

**Comment by Rurik19** [comment]
+1

**Comment by AnatoliiKolesnyk** [comment]
+1

**Comment by snehadarshiniA** [comment]
+1
