### PR TITLE
fix(*): fixes #58, fixes #63, no more 'cannot find module' on windows with typescript 1.6

### LINKED ISSUE #58: Error after migration to 0.14.0 and typescript 1.6.2
After migration to awesome-typescript-loader@0.14.0 and typescript@1.6.2 I'm getting this error:

``` ERROR in [default] C:/Users/tester/Desktop/testing/test/src/app.tsx:4:28
Cannot find module './view/popup/PopupNames'. ```

my config:
```
 { 
    entry: {
        app: ["./src/app.tsx"],
    },
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
    },
    output: {
        path: path.join(__dirname, 'bin'),
        filename: '[name].bundle.js',
        publicPath: '/bin/'
    },
    module: {
        loaders: [
            {
                test: /\.tsx?$/,
                loaders: ['awesome-typescript-loader'],
                include: [path.resolve(__dirname, "src")]
            },
            {
                test: /\.json?$/,
                loaders: ['json-loader']
            }
        ]
    }

};
```
tsconfig: 
```
  "compilerOptions": {
    "target": "es6",
    "sourceMap": true,
    "jsx": "react",
    "experimentalDecorators": true,
    "experimentalAsyncFunctions": true
  },
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "useCache": true
  },
  "files": [
  "./src/app.tsx", "./typings/bundle-tsd.d.ts"
  ]
}
```

### LINKED ISSUE #63: Cannot find module with transitive references
Hi there,
I created this issue for yeoman gulp-angular generator, which uses awesome-typescript-loader:
https://github.com/Swiip/generator-gulp-angular/issues/846

And I'm having two issues here:
1) The imports (import .. from ..;) don't work on Windows at all with TypeScript 1.6.*
2) Transitive imports don't work on Windows not even with TypeScript 1.5.*

Detailed description can be seen in the link. I've seen other issues like this here but don't know what's the current status of them.
Thanks very much. Appreciate your work.
Lukas

### PR DESCRIPTION
**Pull request by johan-gorter**

### CODE REVIEW

**Comment by johan-gorter** [comment]
On my windows machine, this fixes the crash. I am not so sure about the last 2 changed lines.

**Comment by davidmiani** [comment]
I had similar problems to you, but you fix didn't work for me. I've just put up another pull request that works for me. Could you check if it solves your problems as well? Otherwise we may need to combine our changes.

**Comment by s-panferov** [comment]
@johan-gorter please check v0.14.1 and say if it works for you.

**Comment by johan-gorter** [comment]
Verified that v0.14.1 fixes the mentioned issues. Sorry for the delay.
