### ISSUE TITLE
at-loader throws error for an AoT module even though building in dev mode

### ISSUE THREAD

**Issue by papaiatis** [s-panferov/awesome-typescript-loader#371]
I have a MEAN project with Angular 2 and configured dev and prod builds. The latter uses Angular AoT stuff. When I updated ATL from 2.2.4 to 3.0.0 I'm getting the following error when building in dev mode:

ERROR in [at-loader] assets/app/main.aot.ts:6:36
    TS2307: Cannot find module './app.module.ngfactory'.

The file main.aot.ts is the entry point of my production build so nothing to do with dev build.
I have to explicitly exclude this file in tsconfig.json and also exclude main.ts (dev mode) in tsconfig.aot.json.
This wasn't necessary before.

So what has changed?

**Comment by harshes53** [comment]
@papaiatis ditto! 

If I delete `*.aot.ts` and run the dev build it works fine, unless the same as you described, meaning it always runs `*.aot.ts` regardless even if it wasn't mentioned as entry file in webpack config or imported into any module. 

@s-panferov please help!

**Comment by s-panferov** [comment]
Dup of #364
